"""add message

Revision ID: 3c93891fbd2a
Revises: 343dd8fdfc26
Create Date: 2021-02-09 07:17:31.217994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c93891fbd2a'
down_revision = '343dd8fdfc26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('to', sa.String(length=20), nullable=False),
    sa.Column('from_', sa.String(length=20), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=False),
    sa.Column('incoming', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('SEND_PENDING', 'SENT_TO_USER', 'SEND_FAILED', 'RECEIVED_FROM_USER', name='messagestatus'), nullable=False),
    sa.Column('twilio_sid', sa.String(length=100), nullable=True),
    sa.Column('responded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
